name: Build APK
on: [push]

jobs:
  build:
    # استخدام نسخة مستقرة جداً من النظام
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: kivy/buildozer-action@master
        with:
          # أمر clean يمسح أي ملفات تالفة من المحاولات السابقة
          command: buildozer android clean debug
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
